#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

# create xdebug.ini
INI_FILE=/usr/local/etc/php/conf.d/xdebug.ini
docker-xdebug-create-ini ${INI_FILE}
[ -r ${INI_FILE} ] && cat ${INI_FILE}

exec "$@"
