#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

# create xdebug.ini
docker-xdebug-create-ini /usr/local/etc/php/conf.d/xdebug.ini
cat /usr/local/etc/php/conf.d/xdebug.ini

exec "$@"
